### ISSUE TITLE
Was wird denn als Frontabdeckung des 8x8 Blocks benutzt?

### ISSUE THREAD

**Issue by McSpitz** [Nerdiyde/pxlBlck#1]
siehe auch hier? Dachte eine dünne 3d Druck Platte?

**Comment by Nerdiyde** [comment]
Ich hab dazu eine satinierte Plexiglasplatte verwendet. Theoretisch könnte man diese Platte auch drucken, aber die "Maserung" die durchs Drucken entsteht ist dabei leider sichtbar. Ich fand es mit der Plexiglasplatte etwas schicker. :)
Infos zum Aufbau inkl. des benötigten materials habe ich auch hier zusammengetragen: https://nerdiy.de/howto-pxlblck-pxlblck_8x8-aufbauen/#Die_benoetigten_Teile_sammeln

**Comment by McSpitz** [comment]
Ach, ok - stimmt. Nun sehe ich es auch. Ich denke ich werde mal versuchen es zu drucken und schauen wie das aussieht. Danke für die schnelle Rückmeldung.
