### ISSUE TITLE
Ideen zum 8x8

### ISSUE THREAD

**Issue by McSpitz** [Nerdiyde/pxlBlck#2]
Moin moin,

vielleicht ein paar Anregungen zum 8x8 - im Speziellen zur enthaltenen Uhren-Funktion.
Ich würde es super finden, wenn man komplett von 24h auf 12h schalten könnte. Dadurch
bleibt mehr Platz für die Minutenpixel sichtbar.

Wenn man dann noch die Zahlen zentriert, also auch bei 10, 11 und 12 Uhr sowie eine Funktion
einbaut die für AM andere Farben hat als für PM, dann wär das ein cooles Feature, oder?

LG
Alexander

**Comment by Nerdiyde** [comment]
Moin Alexander,
das sollte sich alles umsetzen lassen. Ich hab schon ein paar Ideen wie ich das implementieren kann. :)
Lass das "Issue" hier mal offen, damit ich nicht vergesse mich drum zu kümmern. Sobald ich die Funktionen eingebaut habe, sage ich dann auch hier bescheid. :)
Beste Grüße
Fab

**Comment by Nerdiyde** [comment]
Moin Alexander,
ich habe in das aktuelle Release deine Vorschläge implementiert. Man kann nun zwischen 24 und 12 Stundenmodus umschalten und für vor bzw. nach 12 Uhr andere Stundenfarben festlegen. Lediglich die Zentrierung der einzelnen Ziffern ist noch unverändert. Aber vllt. ist das ja schonmal ein Anfang. :)
Falls du es testen solltest, lass mich gerne wissen ob alles klappt. :)
Beste Grüße
Fab

**Comment by McSpitz** [comment]
Hi Fab,

sehr cool. Werde ich testen!

LG
Alex

Am Sa., 6. Feb. 2021 um 14:56 Uhr schrieb Nerdiy.de <
notifications@github.com>:

**Comment by McSpitz** [comment]
Hi,

beim Wechsel von 11am zu 12am springt die Uhr auf 0Uhr. Das ist noch ein
kleiner Bug.

LG
Alex

Am Sa., 6. Feb. 2021 um 14:56 Uhr schrieb Nerdiy.de <
notifications@github.com>:

**Comment by Nerdiyde** [comment]
Hi Alex,
danke für den Hinweis. Habe den Bug gefixt. 
Update sollte in fünf Minuten verfügbar sein. :)

Beste Grüße
Fab

**Comment by McSpitz** [comment]
Hi Fab,
hab's installiert - dann wollen wir morgen mal sehen ...
LG
Alex

Am Sa., 13. Feb. 2021 um 11:12 Uhr schrieb Nerdiy.de <
notifications@github.com>:

**Comment by McSpitz** [comment]
Also Mittags springt es von 11Uhr auf 12Uhr, dann auf 1. Top!
Nachts aber von 11Uhr auch auf 12Uhr statt auf 0Uhr.
Da ist noch eine Kleinigkeit anzupassen.

Was ich auf jeden Fall noch gut finden würde, eine Routine,
die die Zahlen nimmt, auf eine max. 2 Spalten Abstand rechnet
und zentriert. Dann wär auch die Anzeige hübsch.


Gruß
Alex


Am Sa., 13. Feb. 2021 um 11:12 Uhr schrieb Nerdiy.de <
notifications@github.com>:

**Comment by Nerdiyde** [comment]
Hey Alex,
sorry für die späte Antwort. :)

Zu dem ersten "Bug": Da war ich mir tatsächlich auch sehr unsicher was richtig ist. Ich hatte deswegen nachgeguckt (https://de.wikipedia.org/wiki/2-mal-12-Stunden-Z%C3%A4hlung) und es scheint so als wäre dieser Wechsel so richtig. Also entspricht diesem 2-mal-12-Stunden Zählungsprinzip, dass aus "00:XX" immer "12:XX" gemacht wird.
Oder habe ich Dich falsch verstanden? :)

Das mit der Anzeigenzentrierung habe ich im Hinterkopf. Ich plane gerade eine 16x16 Variante und müsste dann eh nochmal über die Implementierung drüber gucken. Ich versuche das in dem Zuge dann auch zu aktualisieren. 

Ich gebe dann wieder hier bescheid. :)

Beste Grüße
Fab

**Comment by pierrecinema** [comment]
Hallo. Ich wollte von meinem esp8266 zu einem esp32 wechseln. Das bin Image lässt sich zwar Flaschen hat danach aber eine reboot Schleife. Habe es mit diversen flasher probiert,  muss mit dem spiffs zu tun haben,  das scheint zu gross

**Comment by Nerdiyde** [comment]
Hey pierrecinema,
ich habe die binary aktualisiert und auch mal ein paar Infos zum flashen oder (wenn gewünscht) selber kompilieren hinzugefügt. 
Außerdem sind auch die Partitions, bootloader, etc. Infos für den ESP32 enthalten.

Würde mich über eine Rückmeldung (ob alles geklappt hat) freuen.
beste Grüße
Fab

**Comment by pierrecinema** [comment]
Hallo Fab

Danke für die schnelle Antwort

1. Das fertige bin öässt sich nach wie vor nicht flashen, beziehungsweise ist danach in einer Reboot schleife

[2021-05-19 02:41:53,096][ESP8266Loader_spi[1]][espDownloader.py][line:574][ERROR]: ESP32 Chip flash download error esp_write_flash.
[2021-05-19 02:41:53,206][EspDownloadPanel_ESP32_spi(1)][download_panel_info.py][line:494][INFO]: *********************
[2021-05-19 02:41:53,206][EspDownloadPanel_ESP32_spi(1)][download_panel_info.py][line:495][INFO]: pic path: ./RESOURCE/ERROR_S.bmp
[2021-05-19 02:41:53,206][EspDownloadPanel_ESP32_spi(1)][download_panel_info.py][line:496][INFO]: ***********************
[2021-05-19 02:41:53,210][EspDownloadPanel_ESP32_spi(1)][download_panel_info.py][line:524][INFO]: KEY PATH NONE...

![error](https://user-images.githubusercontent.com/8772928/118740578-839c0e80-b84c-11eb-8575-38f6e5e85648.JPG)

**Comment by pierrecinema** [comment]
frage

Ich glaube der fehler kommt von der datei ESP32_ESPEasy_incl_pxlBlck_4M_2M_SPIFFS_NO_OTA.ino.elf. das müsste doch ein bin file sein.

Vielen dank für das coole projekt

**Comment by pierrecinema** [comment]
error: Invalid argument or value after --chip (argument #2)

mit esptool diese fehlermedlung, vielleicht hilft das

**Comment by pierrecinema** [comment]
> Hey pierrecinema,
> ich habe die binary aktualisiert und auch mal ein paar Infos zum flashen oder (wenn gewünscht) selber kompilieren hinzugefügt.
> Außerdem sind auch die Partitions, bootloader, etc. Infos für den ESP32 enthalten.
> 
> Würde mich über eine Rückmeldung (ob alles geklappt hat) freuen.
> beste Grüße
> Fab

Keine idee

**Comment by Nerdiyde** [comment]
Hey pierrecinema,
sorry für die späte Antwort. Habe vergessen auf die letzte Nachricht zu antworten. :/
Ich probiere das gleich nochmal mit dem Flash Tool aus und gebe DIr dann bescheid. :)
Beste Grüße
Fab

**Comment by Nerdiyde** [comment]
@pierrecinema  So, ich habe es jetzt durchprobiert. Habe meine Einstellungen auch als screenshot hierhin gepackt: https://github.com/Nerdiyde/pxlBlck/blob/main/plugin/bin/flash_settings.png
Eigentlich musst du nur anstatt der ...bin.elf die richtige bin datei auswählen. Das ist diese hier: https://github.com/Nerdiyde/pxlBlck/blob/main/plugin/bin/ESP32_ESPEasy_incl_pxlBlck_4M_2M_SPIFFS_NO_OTA.bin
Hoffe es klappt so. :)


@McSpitz :
Hab dich übrigens nicht vergessen. Habe meine 16x16 Matrix mittlerweile aufgebaut. Kannst du nochmal genau beschreiben wie du die Zahlen gerne angeordnet hättest? :)

Beste Grüße
Fabian

**Comment by pierrecinema** [comment]
Werde es morgen testen  Vielen dank. Ich habe hier 4 x16x16 https://youtu.be/wdqJh-EiT60Würde diese nehmen zum testen Gruss Peter 
-------- Ursprüngliche Nachricht --------Von: "Nerdiy.de" ***@***.***> Datum: 29.05.21  15:03  (GMT+01:00) An: Nerdiyde/pxlBlck ***@***.***> Cc: pierrecinema ***@***.***>, Mention ***@***.***> Betreff: Re: [Nerdiyde/pxlBlck] Ideen zum 8x8 (#2) 

@pierrecinema  So, ich habe es jetzt durchprobiert. Habe meine Einstellungen auch als screenshot hierhin gepackt: https://github.com/Nerdiyde/pxlBlck/blob/main/plugin/bin/flash_settings.png

Eigentlich musst du nur anstatt der ...bin.elf die richtige bin datei auswählen. Das ist diese hier: https://github.com/Nerdiyde/pxlBlck/blob/main/plugin/bin/ESP32_ESPEasy_incl_pxlBlck_4M_2M_SPIFFS_NO_OTA.bin

Hoffe es klappt so. :)

@McSpitz :

Hab dich übrigens nicht vergessen. Habe meine 16x16 Matrix mittlerweile aufgebaut. Kannst du nochmal genau beschreiben wie du die Zahlen gerne angeordnet hättest? :)

Beste Grüße

Fabian

**Comment by pierrecinema** [comment]
wollte nicht drängen, sorry und gleichzeitig vielen dank

es lag daran


Eigentlich musst du nur anstatt der ...bin.elf die richtige bin datei auswählen. Das ist diese hier: https://github.com/Nerdiyde/pxlBlck/blob/main/plugin/bin/ESP32_ESPEasy_incl_pxlBlck_4M_2M_SPIFFS_NO_OTA.bin

macht viel mehr spass auf dem Gerät als auf dem lahmen 8266

im Moment betreibe ich die  16x16 Matrix  als 4 x 16x16 
siehe video
https://www.youtube.com/watch?v=wdqJh-EiT60

gruss
