### ISSUE TITLE
4x32 matrix ohne 3d Drucker 

### ISSUE THREAD

**Issue by pierrecinema** [Nerdiyde/pxlBlck#3]
Da ich keinen 3d Drucker habe und trotzdem grosse quadratische Pixel wollte habe ich diese mit einem Schneideplotter und Karton geschnitten.  

![20210519_202316](https://user-images.githubusercontent.com/8772928/120087794-44db4380-c0eb-11eb-9632-a5887ce4256c.jpg)

![20210519_144442](https://user-images.githubusercontent.com/8772928/120087694-6687fb00-c0ea-11eb-8d76-8469e0468bbe.jpg)

![20210519_155537](https://user-images.githubusercontent.com/8772928/120087759-f168f580-c0ea-11eb-9baf-2bf39c1093b0.jpg)

![20210520_200345](https://user-images.githubusercontent.com/8772928/120087815-87048500-c0eb-11eb-9096-1d1267d8e98b.jpg)

Die Unschärfe  an den pixel Ränder auf den Bildern hat zwei Gründe . 1. Handy aber vorallem die bereits grundierte Leihnwand.

**Comment by Nerdiyde** [comment]
Sieht gut aus, Danke für den Hinweis. :)
